//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McTestingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public long Id { get; set; }
        public string ChoiceNumber { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Question RightChoiceQuestion { get; set; }
    }
}
